version: '3.8'

# Production Docker Compose for complete VPN setup
# This file is for testing - use separate server1 and server2 files for production

services:
  internet-server:
    image: m3di/ai-vpn:internet-latest
    container_name: vpn-internet-server
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vpn-server1:
    image: m3di/ai-vpn:server1-latest
    container_name: vpn-server1
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - LOG_LEVEL=info
      - VMESS_UUID=550e8400-e29b-41d4-a716-446655440000
    volumes:
      - vpn-server1-logs:/var/log/xray
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  vpn-server2:
    image: m3di/ai-vpn:server2-latest
    container_name: vpn-server2
    restart: unless-stopped
    ports:
      - "3128:3128"
    environment:
      - LOG_LEVEL=info
      - VMESS_UUID=550e8400-e29b-41d4-a716-446655440000
      - SERVER1_HOST=vpn-server1
      - SERVER1_PORT=443
    volumes:
      - vpn-server2-logs:/var/log/xray
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3128"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - vpn-server1
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  vpn-client:
    image: m3di/ai-vpn:client-latest
    container_name: vpn-client
    restart: unless-stopped
    networks:
      - vpn-network
    depends_on:
      - vpn-server2
      - internet-server
    command: ["sleep", "infinity"]

volumes:
  vpn-server1-logs:
    driver: local
  vpn-server2-logs:
    driver: local

networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 