version: '3.8'

services:
  vpn-server2:
    image: m3di/ai-vpn:server2-latest
    container_name: vpn-server2
    restart: unless-stopped
    ports:
      - "3128:3128"
    environment:
      - LOG_LEVEL=info
      - VMESS_UUID=550e8400-e29b-41d4-a716-446655440000
      - SERVER1_HOST=SERVER1_IP_PLACEHOLDER
      - SERVER1_PORT=443
    volumes:
      - vpn-server2-logs:/var/log/xray
    networks:
      - vpn-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3128"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  vpn-server2-logs:
    driver: local

networks:
  vpn-network:
    driver: bridge 